<a href="https://colab.research.google.com/github/ImNick23/Test/blob/master/Copy_of_recommend_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Import warnings
import warnings
warnings.filterwarnings('ignore')

In [0]:
#Importing numpy, pandas and matplotlib packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# importing  data
beer= pd.read_csv("https://raw.githubusercontent.com/ImNick23/file/master/beer_data.csv")
beer.head()

beer_beerid review_profilename  review_overall
0        48215            stcules             3.0
1        52159            oline73             3.0
2        52159       alpinebryant             3.0
3        52159            rawthar             4.0
4        52159        RangerClegg             3.5

**Data Preparation**

In [5]:
#Check shape and null values in data
print(beer.shape)
beer.isnull().sum()

(475984, 3)


beer_beerid             0
review_profilename    100
review_overall          0
dtype: int64

In [6]:
#Remove all null values present in data
beer = beer.dropna(how='any',axis=0)
print(beer.shape)
beer.isnull().sum()

(475884, 3)


beer_beerid           0
review_profilename    0
review_overall        0
dtype: int64

In [7]:
#checking number of unique values in df
beer.nunique()

beer_beerid           40304
review_profilename    22497
review_overall           10
dtype: int64

In [8]:
#Checking duplicate values for same profile with same beer id
beer.duplicated(subset=["beer_beerid","review_profilename"], keep='first').sum()

1422

In [9]:
#Removing duplicate values for same profile with same beer id
beer.drop_duplicates(subset = ["beer_beerid","review_profilename"], keep = 'first', inplace = True)
beer.duplicated(subset=["beer_beerid","review_profilename"], keep='first').sum()

0

In [10]:
#Checking shape again
print(beer.shape)
beer.head()

(474462, 3)


beer_beerid review_profilename  review_overall
0        48215            stcules             3.0
1        52159            oline73             3.0
2        52159       alpinebryant             3.0
3        52159            rawthar             4.0
4        52159        RangerClegg             3.5

In [12]:
#Removing data for all the beers which have less than 50 revivews
beer=beer.groupby('beer_beerid').filter(lambda x : len(x)>50)
beer.shape

(294197, 3)

**Data exploration**

In [19]:
#Check unique values and count of beers for each rating present
print(beer.nunique())
beer.groupby('review_overall').count()

beer_beerid            2028
review_profilename    19447
review_overall            9
dtype: int64


beer_beerid  review_profilename
review_overall                                 
1.0                    1682                1682
1.5                    1873                1873
2.0                    5987                5987
2.5                    9038                9038
3.0                   26895               26895
3.5                   51606               51606
4.0                  110316              110316
4.5                   66724               66724
5.0                   20076               20076

In [97]:
#The average beer ratings
print(beer.groupby('beer_beerid').review_overall.mean())

beer_beerid
5        3.553097
6        3.711462
7        3.317073
10       3.883028
14       3.830508
           ...   
74272    3.648148
74323    3.920290
74390    3.718750
74986    4.217054
75086    3.660494
Name: review_overall, Length: 2028, dtype: float64


In [103]:
#The average user ratings
beer.groupby('review_profilename').review_overall.mean()

review_profilename
0110x011       4.333333
01Ryan10       5.000000
04101Brewer    4.000000
05Harley       4.116667
0beerguy0      4.166667
                 ...   
zymurgy4all    3.703704
zymurgywhiz    4.250000
zythus         5.000000
zyzygy         4.166667
zzajjber       5.000000
Name: review_overall, Length: 19447, dtype: float64

In [23]:
#The average number of ratings given to the beers
beer.groupby('beer_beerid').count().review_overall.mean()

145.06755424063115

In [24]:
#The average number of ratings given by the users
beer.groupby('review_profilename').count().review_overall.mean()

15.128143158327763

**Model Building**

In [0]:
#Split into train-test
from sklearn.model_selection import train_test_split
train, test = train_test_split(beer, test_size=0.30, random_state=31)

In [26]:
print(train.shape)
print(test.shape)

(205937, 3)
(88260, 3)


In [0]:
# pivot ratings into beer features
df_beer_features = train.pivot(index='review_profilename',columns='beer_beerid',values='review_overall').fillna(0)

In [28]:
df_beer_features.head()

beer_beerid         5      6      7      10     ...  74323  74390  74986  75086
review_profilename                              ...                            
0110x011              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
01Ryan10              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
04101Brewer           0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
05Harley              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
0beerguy0             0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0

[5 rows x 2028 columns]

In [0]:
#Make copy of train and test
dummy_train = train.copy()
dummy_test = test.copy()

In [30]:
print(dummy_train.head())
dummy_train.shape

        beer_beerid review_profilename  review_overall
162658         5948    TheEclecticGent             4.5
217111         2961          Franchise             4.0
29063         54089              Jayli             3.0
24752          3558          terrabyte             3.5
312729        20768      darklordlager             4.0


(205937, 3)

In [0]:
#Make all non reviewed cell as 1 and rest all 0 for train and vice versa for test.
dummy_train['review_overall'] = dummy_train['review_overall'].apply(lambda x: 0 if x >= 1 else 1)
dummy_test['review_overall'] = dummy_test['review_overall'].apply(lambda x: 1 if x >=1 else 0)

In [0]:
# The beer not rated by user is marked as 1 for prediction. 
dummy_train = dummy_train.pivot(
    index='review_profilename',
    columns='beer_beerid',
    values='review_overall'
).fillna(1)

# The beer not rated by user is marked as 0 for evaluation. 
dummy_test = dummy_test.pivot(
    index='review_profilename',
    columns='beer_beerid',
    values='review_overall'
).fillna(0)

In [33]:
dummy_train.head()

beer_beerid         5      6      7      10     ...  74323  74390  74986  75086
review_profilename                              ...                            
0110x011              1.0    1.0    1.0    1.0  ...    1.0    1.0    1.0    1.0
01Ryan10              1.0    1.0    1.0    1.0  ...    1.0    1.0    1.0    1.0
04101Brewer           1.0    1.0    1.0    1.0  ...    1.0    1.0    1.0    1.0
05Harley              1.0    1.0    1.0    1.0  ...    1.0    1.0    1.0    1.0
0beerguy0             1.0    1.0    1.0    1.0  ...    1.0    1.0    1.0    1.0

[5 rows x 2028 columns]

In [34]:
dummy_test.head()

beer_beerid         5      6      7      10     ...  74323  74390  74986  75086
review_profilename                              ...                            
0110x011              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
05Harley              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
0tt0                  0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
1001111               0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
100floods             0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0

[5 rows x 2028 columns]

In [0]:
#Pivot beer features
beer_features = train.pivot(
    index='review_profilename',
    columns='beer_beerid',
    values='review_overall'
)

In [36]:
beer_features.head()

beer_beerid         5      6      7      10     ...  74323  74390  74986  75086
review_profilename                              ...                            
0110x011              NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN
01Ryan10              NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN
04101Brewer           NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN
05Harley              NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN
0beerguy0             NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN

[5 rows x 2028 columns]

In [37]:
#Take df_subtracted which is mean of nan values subtracted from original df
mean = np.nanmean(beer_features, axis=1)
df_subtracted = (beer_features.T-mean).T
df_subtracted=df_subtracted.fillna(0)
df_subtracted.head()

beer_beerid         5      6      7      10     ...  74323  74390  74986  75086
review_profilename                              ...                            
0110x011              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
01Ryan10              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
04101Brewer           0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
05Harley              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
0beerguy0             0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0

[5 rows x 2028 columns]

In [0]:
#Create cosine Similarity matrix
from sklearn.metrics.pairwise import pairwise_distances

# User Similarity Matrix
user_correlation = 1 - pairwise_distances(df_subtracted, metric='cosine')

In [39]:
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [40]:
#Remove all negative recommondation
user_correlation[user_correlation<0]=0
user_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

**Prediction for user based**

In [41]:
#Prediction for user based model
user_predicted_ratings = np.dot(user_correlation, beer_features.fillna(0))
user_predicted_ratings

array([[1.18210979, 2.39586718, 2.00712931, ..., 1.30620554, 2.19226756,
        1.58426839],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.56729534, 5.22367115, 2.53076101, ..., 0.44452145, 0.71906464,
        2.19279431],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [42]:
user_predicted_ratings.shape

(17202, 2028)

In [43]:
#multiply user prediction with dummy train to get final ratings
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

beer_beerid            5         6         7      ...     74390     74986     75086
review_profilename                                ...                              
0110x011            1.182110  2.395867  2.007129  ...  1.306206  2.192268  1.584268
01Ryan10            0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
04101Brewer         0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
05Harley            1.431752  4.224999  2.486638  ...  0.755234  4.726285  2.286082
0beerguy0           0.667724  2.713345  1.434856  ...  0.442603  0.242318  0.293490

[5 rows x 2028 columns]

In [44]:
#Test model with one of the user with top 5 recommended beers
user_final_rating.iloc[3].sort_values(ascending=False)[0:5]

beer_beerid
412      30.017483
17112    28.251250
4083     27.088169
19960    26.874796
1904     24.497512
Name: 05Harley, dtype: float64

In [45]:
#Use transponse of beer features for item based model
beer_item_features = train.pivot(
    index='review_profilename',
    columns='beer_beerid',
    values='review_overall'
).T

beer_item_features.head()

review_profilename  0110x011  01Ryan10  04101Brewer  ...  zythus  zyzygy  zzajjber
beer_beerid                                          ...                          
5                        NaN       NaN          NaN  ...     NaN     NaN       NaN
6                        NaN       NaN          NaN  ...     NaN     NaN       NaN
7                        NaN       NaN          NaN  ...     NaN     NaN       NaN
10                       NaN       NaN          NaN  ...     NaN     NaN       NaN
14                       NaN       NaN          NaN  ...     NaN     NaN       NaN

[5 rows x 17202 columns]

In [0]:
#Take subtracted df which is mean of nan values subtracted from original df
mean = np.nanmean(beer_item_features, axis=1)
df_item_based_subtracted = (beer_item_features.T-mean).T

In [47]:
df_item_based_subtracted.head()

review_profilename  0110x011  01Ryan10  04101Brewer  ...  zythus  zyzygy  zzajjber
beer_beerid                                          ...                          
5                        NaN       NaN          NaN  ...     NaN     NaN       NaN
6                        NaN       NaN          NaN  ...     NaN     NaN       NaN
7                        NaN       NaN          NaN  ...     NaN     NaN       NaN
10                       NaN       NaN          NaN  ...     NaN     NaN       NaN
14                       NaN       NaN          NaN  ...     NaN     NaN       NaN

[5 rows x 17202 columns]

In [48]:
#Get cosine  Item Similarity Matrix
from sklearn.metrics.pairwise import pairwise_distances

# Item Similarity Matrix
item_correlation = 1 - pairwise_distances(df_item_based_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[ 1.00000000e+00  8.29686245e-03  2.31720924e-03 ...  7.95984223e-05
   1.41341239e-02 -3.28010645e-03]
 [ 8.29686245e-03  1.00000000e+00  1.74066299e-03 ... -1.34282657e-02
   2.26833774e-03  4.21673842e-03]
 [ 2.31720924e-03  1.74066299e-03  1.00000000e+00 ...  0.00000000e+00
   8.66663720e-04  2.16803081e-02]
 ...
 [ 7.95984223e-05 -1.34282657e-02  0.00000000e+00 ...  1.00000000e+00
   9.49920731e-03  2.53744976e-02]
 [ 1.41341239e-02  2.26833774e-03  8.66663720e-04 ...  9.49920731e-03
   1.00000000e+00 -1.74653081e-02]
 [-3.28010645e-03  4.21673842e-03  2.16803081e-02 ...  2.53744976e-02
  -1.74653081e-02  1.00000000e+00]]


In [49]:
#Take only positive values to avoid negative recommedation
item_correlation[item_correlation<0]=0
item_correlation

array([[1.00000000e+00, 8.29686245e-03, 2.31720924e-03, ...,
        7.95984223e-05, 1.41341239e-02, 0.00000000e+00],
       [8.29686245e-03, 1.00000000e+00, 1.74066299e-03, ...,
        0.00000000e+00, 2.26833774e-03, 4.21673842e-03],
       [2.31720924e-03, 1.74066299e-03, 1.00000000e+00, ...,
        0.00000000e+00, 8.66663720e-04, 2.16803081e-02],
       ...,
       [7.95984223e-05, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 9.49920731e-03, 2.53744976e-02],
       [1.41341239e-02, 2.26833774e-03, 8.66663720e-04, ...,
        9.49920731e-03, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 4.21673842e-03, 2.16803081e-02, ...,
        2.53744976e-02, 0.00000000e+00, 1.00000000e+00]])

**Prediction for Item based**

In [50]:
#Find predicted ratings with dot product
item_predicted_ratings = np.dot((df_item_based_subtracted.fillna(0).T),item_correlation)
item_predicted_ratings

array([[ 0.00242126,  0.01702397,  0.00016852, ...,  0.05174728,
         0.05323234,  0.02654053],
       [ 0.        ,  0.        ,  0.00491195, ...,  0.02092873,
         0.01038159,  0.        ],
       [ 0.        , -0.00269408, -0.00105854, ...,  0.        ,
         0.        , -0.00526907],
       ...,
       [ 0.03007527,  0.        ,  0.01807933, ...,  0.00980537,
         0.02202895,  0.01431684],
       [ 0.00020038,  0.01236403,  0.00376191, ...,  0.        ,
         0.0016721 ,  0.00658889],
       [ 0.        ,  0.00919882,  0.01291677, ...,  0.        ,
         0.        ,  0.        ]])

In [51]:
item_predicted_ratings.shape

(17202, 2028)

In [52]:
dummy_train.shape

(17202, 2028)

In [53]:
#Multiply predicted ratings with dummy to get final ratings
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

beer_beerid            5         6         7      ...     74390     74986     75086
review_profilename                                ...                              
0110x011            0.002421  0.017024  0.000169  ...  0.051747  0.053232  0.026541
01Ryan10            0.000000  0.000000  0.004912  ...  0.020929  0.010382  0.000000
04101Brewer         0.000000 -0.002694 -0.001059  ...  0.000000  0.000000 -0.005269
05Harley           -0.021452 -0.001032  0.021830  ... -0.001501 -0.028914  0.023313
0beerguy0           0.007324 -0.010586  0.010634  ...  0.001552  0.000730  0.002728

[5 rows x 2028 columns]

In [71]:
#Model test for item based
item_final_rating.iloc[3].sort_values(ascending=False)[0:5]

beer_beerid
48194    0.088989
4878     0.070944
37966    0.068034
62328    0.066027
16439    0.063243
Name: 05Harley, dtype: float64

In [57]:
item_final_rating.head(10)

beer_beerid                5         6      ...     74986     75086
review_profilename                          ...                    
0110x011            2.421263e-03  0.017024  ...  0.053232  0.026541
01Ryan10            0.000000e+00  0.000000  ...  0.010382  0.000000
04101Brewer         0.000000e+00 -0.002694  ...  0.000000 -0.005269
05Harley           -2.145208e-02 -0.001032  ... -0.028914  0.023313
0beerguy0           7.323503e-03 -0.010586  ...  0.000730  0.002728
0runkp0s            0.000000e+00  0.010005  ...  0.000000  0.003173
0tt0                1.298360e-02  0.008988  ...  0.017744  0.008686
1000Bottles        -3.225851e-03  0.080186  ...  0.005431 -0.001822
100floods           2.119187e-02  0.039402  ... -0.049134  0.016953
1050Sudz           -4.439003e-07 -0.000038  ...  0.000000  0.000000

[10 rows x 2028 columns]

In [58]:
user_final_rating.head(10)

beer_beerid            5         6         7      ...     74390     74986     75086
review_profilename                                ...                              
0110x011            1.182110  2.395867  2.007129  ...  1.306206  2.192268  1.584268
01Ryan10            0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
04101Brewer         0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
05Harley            1.431752  4.224999  2.486638  ...  0.755234  4.726285  2.286082
0beerguy0           0.667724  2.713345  1.434856  ...  0.442603  0.242318  0.293490
0runkp0s            0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
0tt0                2.188771  6.958947  4.654329  ...  1.020663  6.088229  3.230929
1000Bottles         0.502975  1.003797  2.444376  ...  0.328739  0.843008  1.024841
100floods           0.749614  1.282038  1.346043  ...  0.550781  0.927943  0.847255
1050Sudz            0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000

[10 rows x 2028 columns]

In [99]:
# top 5 beers that you would recommend to the users 'cokes', 'genog' and 'giblet' using both the models.
print(user_final_rating.loc['cokes'].sort_values(ascending=False)[0:5])
print(item_final_rating.loc['cokes'].sort_values(ascending=False)[0:5])
print(user_final_rating.loc['genog'].sort_values(ascending=False)[0:5])
print(item_final_rating.loc['genog'].sort_values(ascending=False)[0:5])
print(user_final_rating.loc['giblet'].sort_values(ascending=False)[0:5])
item_final_rating.loc['giblet'].sort_values(ascending=False)[0:5]

beer_beerid
412     42.048229
1093    38.781419
1708    36.911971
4083    36.850615
34      36.494164
Name: cokes, dtype: float64
beer_beerid
356      0.712988
1713     0.640622
38149    0.631892
34363    0.599630
31323    0.594910
Name: cokes, dtype: float64
beer_beerid
2093    33.613647
1093    32.375077
1013    29.789423
34      29.485823
92      29.386374
Name: genog, dtype: float64
beer_beerid
40956    0.246236
45368    0.236574
1959     0.226124
27476    0.225972
27143    0.203829
Name: genog, dtype: float64
beer_beerid
2093    63.411020
104     62.002390
412     61.935268
1093    56.511968
34      53.872070
Name: giblet, dtype: float64


beer_beerid
40798    0.080821
48434    0.061476
31613    0.060388
3279     0.059108
67040    0.056448
Name: giblet, dtype: float64

**Comparing the performance of the two models using test data**

In [56]:
test_beer_features = test.pivot(
    index='review_profilename',
    columns='beer_beerid',
    values='review_overall'
)
mean = np.nanmean(test_beer_features, axis=1)
test_df_subtracted = (test_beer_features.T-mean).T

# User Similarity Matrix
test_user_correlation = 1 - pairwise_distances(test_df_subtracted.fillna(0), metric='cosine')
test_user_correlation[np.isnan(test_user_correlation)] = 0
print(test_user_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
test_user_correlation[test_user_correlation<0]=0
test_user_predicted_ratings = np.dot(test_user_correlation, test_beer_features.fillna(0))
test_user_predicted_ratings

array([[0.25759248, 1.03114226, 0.42726579, ..., 0.16461519, 0.60528718,
        0.74483352],
       [0.17607375, 0.59829136, 0.41797999, ..., 0.71338242, 0.        ,
        0.26969114],
       [0.35672692, 0.63287196, 0.06750944, ..., 0.6041211 , 0.        ,
        0.07923394],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.53947716, 1.81844717, 0.45549682, ..., 0.00343226, 0.73337831,
        1.22483534],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [0]:
test_user_final_rating = np.multiply(test_user_predicted_ratings,dummy_test)

In [0]:
test_user_final_rating.head()

beer_beerid         5      6      7      10     ...  74323  74390  74986  75086
review_profilename                              ...                            
0110x011              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
05Harley              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
0tt0                  0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
1001111               0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
100floods             0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0

[5 rows x 2028 columns]

In [0]:
#Scaling to get original ratings in data
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = test_user_final_rating.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=([0,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0]))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(copy=True,
             feature_range=[0, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0])
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [0]:
#Finding RMSE for user based
test_ = user_based_test.pivot(
    index='review_profilename',
    columns='beer_beerid',
    values='review_overall'
)
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))
rmse = (sum(sum((test_ - y )**2))/total_non_nan)**0.5
print(rmse)

3.6324965406761134


In [0]:
test_beer_features = user_based_test.pivot(
    index='review_profilename',
    columns='beer_beerid',
    values='review_overall'
).T

mean = np.nanmean(test_beer_features, axis=1)
test_df_item_subtracted = (test_beer_features.T-mean).T

test_item_correlation = 1 - pairwise_distances(test_df_item_subtracted.fillna(0), metric='cosine')
test_item_correlation[np.isnan(test_item_correlation)] = 0
test_item_correlation[test_item_correlation<0]=0

In [0]:
test_item_predicted_ratings = (np.dot(test_item_correlation, test_beer_features.fillna(0))).T
test_item_final_rating = np.multiply(test_item_predicted_ratings,dummy_test)
test_item_final_rating.head()

beer_beerid         5      6      7      10     ...  74323  74390  74986  75086
review_profilename                              ...                            
0110x011              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
05Harley              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
0tt0                  0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
1001111               0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
100floods             0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0

[5 rows x 2028 columns]

In [0]:
test_ = user_based_test.pivot(
    index='review_profilename',
    columns='beer_beerid',
    values='review_overall'
)

In [0]:
#Scaling to get original ratings
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = test_item_final_rating.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=([0,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0]))
print(scaler.fit(X))
y = (scaler.transform(X))


test_ = user_based_test.pivot(
    index='review_profilename',
    columns='beer_beerid',
    values='review_overall'
)

# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

MinMaxScaler(copy=True,
             feature_range=[0, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0])


In [0]:
#RMSE score for item based model
rmse = (sum(sum((test_ - y )**2))/total_non_nan)**0.5
print(rmse)

3.645549453427868


*Since using user based has less value of RMSE, it will perform better than item based.*